server:
  port: 8082
spring:
  application:
    name: deposit-product-service
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://127.0.0.1:3306/corporate_deposit_ai?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD}
  flyway:
    table: flyway_schema_history_product
    baseline-on-migrate: true
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        enabled: ${NACOS_ENABLED:true}

